name: For each commit and PR
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: -v --config .golangci.yml --timeout=5m --out-format=colored-line-number
        version: latest
